# Generated by Django 3.1.7 on 2021-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=50)),
                ('user_age', models.IntegerField()),
                ('user_occupation', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_state', models.CharField(max_length=50)),
                ('user_zipcode', models.IntegerField()),
            ],
        ),
    ]
