# Generated by Django 3.1.7 on 2021-04-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0002_auto_20210420_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.CharField(error_messages={'unique': 'Account with the email already exists'}, max_length=100, unique=True),
        ),
    ]
